// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhdbjtlzfoyzslhzkplu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoZGJqdGx6Zm95enNsaHprcGx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4OTY0ODcsImV4cCI6MjA2NzQ3MjQ4N30.paGB_hXQH09ja-kMFWzvJB96npCX3uRXFcpzF-UlTgw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});